### ISSUE TITLE
Tagging asset releases

### ISSUE THREAD

**Issue by Soliah** [ember-cli/ember-cli-deploy#110] opened 2015-03-16 22:41 UTC
Looks like a lot is happening for 0.5.0 in #47 but is there a way I can use the tagging adapters in an asset adapter right now?

The problem I'm having right now is the S3 asset adapter simply uploads the newly fingerprinted assets to the same folder over and over again with no mechanism to clean up older releases. I end up with lots of app-fingerprint.js and vendor-fingerprint.js files on S3.

Ideally I'd like a way to upload asset releases to a sub directory named the same as the tag, so 

```
bucket/app:sha/assets/vendor.js
bucket/app:sha/assets/app.js
```

**Comment by Soliah** [comment] 2015-03-16 22:45
Not sure if I should've raised this in the ember-deploy-s3 repo? I had a look at the source but it looks like asset-adapters don't get given the default tagging adapter?

**Comment by LevelbossMike** [comment] 2015-03-17 07:32
Thanks for raising this issue.

As you noted, to keep the ember-cli-deploy repo issues cleaner it would be better to raise plugin specific issues in their respective issue trackers.

Concerning your question. It is actually by design that old releases don't get cleaned up.

1. S3 Hosting is 'cheap' and there is no need to clean them up
2. It is not that trivial to know which assets to clean up because assets only change their fingerprint when the underlying file changes and thus index.html may reference 'old' asset-files.
3. It is easier to rollback when old assets are still available in your app's asset bucket.

I get why some people may think it was important to clean up their assets but I don't think you get much benefit by doing so because:

a) It's hard to do in the happy path (only vendor.js, app.js etc.) :trollface:

b) It get's really hard when throwing other assets like language-files, svgs into the mix that are referenced inside app.js

c) Your suggested approach by referencing `app:sha` in the asset urls would need rewrite the prepend option in the app's fingerprint-options dynamically when doing the ember build

d) If you decide to go down this route because you plan on saving money by implementing this approach I think it may be the case that you'd need to upload more files because you'd always need to sync all the assets into the `app:sha`-directories inside your bucket. And that are actually more files uploaded than would be necessary when just dumping everything in one bucket.

If you nevertheless feel that this is an asset-upload strategy worth pursuing (which may be the case for your specific needs) I suggest to implement this in a different asset-upload-plugin because this would need a pretty different approach for uploading files than `ember-deploy-s3` and I think it's best to keep different upload strategies in different plugins.

**Comment by lukemelia** [comment] 2015-10-30 14:54
Closing since 0.5 is out now. If this issue is still of value, please open one against the new ember-cli-deploy-s3 plugin: https://github.com/ember-cli-deploy/ember-cli-deploy-s3

**Closed by lukemelia** 2015-10-30 14:54 UTC
