### ISSUE TITLE
command line params not trimmed

### ISSUE THREAD

**Issue by jpaas** [ember-cli/ember-cli-deploy#150] opened 2015-06-09 13:45 UTC
If I run a deploy command such as `ember deploy --environment staging ` with a trailing space at the end, my deploy will fail because my environment is set to "staging " instead of "staging". Command line params that are not enclosed in quotes should probably be trimmed.

**Comment by duizendnegen** [comment] 2015-07-11 22:56
Unable to reproduce this bug on my Win7 machine. Passing in `--environment staging ` with the space included selects the `staging` environment. Possibly *nix systems behave differently here?

**Comment by ghedamat** [comment] 2016-01-24 02:08
@jpaas closing for now, I can't reproduce on osx either and ecd changed quite a bit since this was reported

please reopen if this is still broken for you and we'll try to get a fix!

**Closed by ghedamat** 2016-01-24 02:08 UTC
Labels: bug

**Comment by jpaas** [comment] 2016-01-25 19:20
Actually it seems to be fixed for me now.  Thanks @ghedamat
