### ISSUE TITLE
When deploy fails and --activate succeeds, a success code is returned

### ISSUE THREAD

**Issue by JoshSmith** [ember-cli/ember-cli-deploy#327] opened 2015-12-14 19:43 UTC
It appears that when a deploy fails but activation succeeds with the `--activate` command, the return is a success code for the activation. On my CI server this looks to me like a false positive.

Is this the expected behavior? Or should the whole thing fail? My guess is you don't even want to proceed with the activation in the event of a failing deploy.

**Comment by ghedamat** [comment] 2015-12-14 19:45
@JoshSmith it should definitely fail and not activate

I don't remember seeing this one, but thanks for reporting, we'll try to reproduce it and report back

**Comment by JoshSmith** [comment] 2015-12-14 19:48
@ghedamat I can tell you exactly what it failed on: I had provided a username (which is included by default in Redis Cloud's URL on Heroku). This username fails with the same error seen here: https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/issues/9

While the username is a whole separate issue, I planned to take the URL dynamically from Heroku with my API key and use that for the Redis URL. Given that this URL _could_ change, I'd prefer that over hamfisting it manually into my CI's env.

**Comment by ghedamat** [comment] 2015-12-16 00:41
@JoshSmith I think I've been able to reproduce, looks like the redis plugin is swallowing the error and preventing the pipeline from aborting, will investigate more soon

**Comment by ghedamat** [comment] 2015-12-16 01:58
ok, here's the current status of my investigation

this is a problem related ONLY to `ember-cli-deploy-redis`

with the current version of `then-redis` that we're using in that plugin, when redis returns a parse error the `redis` library used doesn't seem to send the proper `error` event, because of that `then-redis `doesn't receive it 
and we don't get a rejected promise, so we don't abort the pipeline.

It looks like `then-redis` is not maintained anymore https://github.com/mjackson/then-redis/issues/51 and that the current consensus is to use node-redis directly with `bluebird` 

https://github.com/NodeRedis/node_redis#promises

I guess if I'm right and this is the problem we'll need a good PR to ember-cli-deploy-redis


/cc @achambers @lukemelia @JoshSmith

**Comment by achambers** [comment] 2015-12-16 07:40
Thanks for investigating @ghedamat

**Comment by lukemelia** [comment] 2015-12-30 14:19
@ghedamat should we move this to `ember-cli-deploy/ember-cli-deploy-redis`?

**Comment by ghedamat** [comment] 2015-12-30 16:10
@lukemelia I think so

**Comment by jordanyee** [comment] 2016-01-19 08:03
For anyone else looking: this was moved to https://github.com/ember-cli-deploy/ember-cli-deploy-redis/issues/36.

**Comment by achambers** [comment] 2016-02-04 16:07
Closing this issue now in favour of ember-cli-deploy/ember-cli-deploy-redis/issues/51

**Closed by achambers** 2016-02-04 16:07 UTC
Labels: bug
