### ISSUE TITLE
Option to fail quietly if revision is already deployed

### ISSUE THREAD

**Issue by trianglegrrl** [ember-cli/ember-cli-deploy#123] opened 2015-03-30 16:00 UTC
Sorry, another feature request! We are running ember-cli-deploy in scripts (used by our QA folks, not devs), and checking for exit status. 

The problem is, if we run an `ember deploy -e staging` on a revision that's already in our redis store, it fails and exits with error code 1. We'd love an option to control that so it could just say it was successful even if it didn't have to do any work. Alternately, a simple way to check if a revision exists (e.g. `ember deploy:list REVISION`, that exits with a 0 if it is found and a 1 if it it isn't) would be great.

**Comment by achambers** [comment] 2015-03-30 16:43
Thanks for the suggestions @trianglegrrl .  Will have a chat with the others and see what we can come up with.  Alternatively, feel free to submit a PR to start a discussion yourself :+1:

**Comment by LevelbossMike** [comment] 2015-03-30 16:44
thx. this is most likely a duplicate of https://github.com/ember-cli/ember-cli-deploy/issues/105

we are already thinking about adding a force option to deployments which should fix your issue as well.

**Comment by LevelbossMike** [comment] 2015-03-30 16:44
closing in favor of https://github.com/ember-cli/ember-cli-deploy/issues/105

**Closed by LevelbossMike** 2015-03-30 16:44 UTC
