### ISSUE TITLE
Deploying to redis via an ssh tunnel

### ISSUE THREAD

**Issue by mnutt** [ember-cli/ember-cli-deploy#108] opened 2015-03-16 04:13 UTC
My team has a deployment process very similar to ember-cli-deploy's default, but our redis server isn't directly accessible from our local machines due to firewall rules. The options I see are:

* Just remind devs to have a tunnel set up between their machine and redis. It's simplest, but I don't love having local machines with always-on direct access to our production redis servers.
* Some combination of ember-deploy-ssh-index and ember-deploy-redis to ssh to the redis machine and run redis commands. This is what we do currently via a homegrown script but it's kind of a mess to pipe redis commands through bash.
* Use ember-deploy-redis and wrap then-redis to set up an ssh tunnel from an ephemeral port to the redis port on the remote server for the duration of the deploy. I'm favoring this option, but am curious if you think it's better as its own deploy plugin or if it could be merged into ember-deploy-redis.  

The extra options could look like:
```
  development: {
    store: {
      type: 'redis', // the default store is 'redis'
      host: 'remoteHost',
      port: 6379,
      ssh: {
        localPort: 38596, // if not set, one is randomly chosen between 32768 and 65535
        username: 'deploy',
        privateKey: ...,
      }
    }
```

(I opened the issue here since I know there are a lot of big changes coming to the plugin system, but I can move it to the ember-deploy-s3 repo if that is a better place for it.)

**Comment by lukemelia** [comment] 2015-03-16 05:04
Seems to me that having this as an option for ember-(cli-)deploy-redis makes sense, but I'd like to hear @LevelbossMike's input.

**Comment by blimmer** [comment] 2015-03-16 14:36
As we migrate to ember-cli-deploy(-redis) we will need to resolve this exact same problem because our production Redis servers are limited similarly to @mnutt 's environment. I'm in favor of the last bullet point of supporting opening a tunnel for the duration of the deploy and merging into ember-deploy-redis.

**Comment by LevelbossMike** [comment] 2015-03-16 15:08
this seems like a useful addition to ember-deploy-redis. And like a use-case that should be supported by the plugin because it's annoying for everyone to set this up themselves and there are definitely a lot of people that need it.

**Comment by ungue** [comment] 2015-03-26 07:55
:+1: for this. This is exactly what Im looking for.

**Comment by trianglegrrl** [comment] 2015-03-26 15:48
:+1: from us, too. To our interests, this is indeed relevant.

**Comment by blimmer** [comment] 2015-03-26 15:50
Since this is Redis specific, the issue is now [here](https://github.com/LevelbossMike/ember-deploy-redis/issues/4) . @LevelbossMike think it's OK to close this issue and track with the ember-deploy-redis issue?

**Comment by LevelbossMike** [comment] 2015-03-26 17:52
yup. closing in favor for https://github.com/LevelbossMike/ember-deploy-redis/issues/4

**Closed by LevelbossMike** 2015-03-26 17:52 UTC
