### ISSUE TITLE
'Unexpected token u' when deploying

### ISSUE THREAD

**Issue by jpaas** [ember-cli/ember-cli-deploy#137] opened 2015-05-21 20:18 UTC
I'm using ember-cli-deploy 0.4.1 and ember-deploy-s3 0.0.3. This did work at one time but now I'm getting the following error:

```
$ ember deploy --environment staging​
version: 0.2.5
Built project successfully. Stored in "dist/".
Unexpected token u
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Class.module.exports.CoreObject.extend._materialize (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/lib/models/config.js:60:29)
    at Class.module.exports.Task.extend.uploadAssets (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/lib/tasks/assets.js:60:22)
    at lib$rsvp$$internal$$tryCatch (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickDomainCallback (node.js:381:11)
```

Any ideas what the problem could be?

**Comment by flecno** [comment] 2015-05-22 18:20
How your deploy config looks?

**Comment by jpaas** [comment] 2015-05-22 18:42
It looks something like...

```javascript
module.exports = {
  staging: {
    buildEnv: 'staging',
    store: {
      type: 'S3',
      accessKeyId: process.env['AWS_ACCESS_KEY'],
      secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
      bucket: 'hcpstaging',
      region: 'us-west-2'
    },
    assets: {
      type: 's3',
      accessKeyId: process.env['AWS_ACCESS_KEY'],
      secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
      bucket: 'hcpstaging.assets',
      region: 'us-west-2'
    }
  },

  production: {
    buildEnv: 'production',
    store: {
      type: 'S3',
      accessKeyId: process.env['AWS_ACCESS_KEY'],
      secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
      bucket: 'hcpwebapp',
      region: 'us-west-2'
    },
    assets: {
      type: 's3',
      accessKeyId: process.env['AWS_ACCESS_KEY'],
      secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
      bucket: 'hcpwebapp.assets',
      region: 'us-west-2'
    }
  }

}
```

**Comment by lukemelia** [comment] 2015-05-27 12:55
That error usually occurs when JS is trying to JSON.parse `undefined`. It is a bug in ember-cli-deploy in as much as the error message should be better.

It seems like the most likely thing that would lead to this error is a mismatch between the passed environment name and the config file node name.

**Comment by lukemelia** [comment] 2015-05-27 12:57
Try running with `EMBER_VERBOSE_ERRORS=true` environment variable. i.e. `EMBER_VERBOSE_ERRORS=true ember deploy --environment staging`

**Comment by jpaas** [comment] 2015-05-27 13:37
omg I just went back to try it with `EMBER_VERBOSE_ERRORS=true` and this time it actually worked and published.

But I now have a different error when trying to active my newly published build:

```
$ EMBER_VERBOSE_ERRORS=true ember deploy:activate --revision hcp-webapp:5ec2c0b --environment staging​
version: 0.2.5
undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.Task.extend.run (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/lib/tasks/activate.js:32:19)
    at Class.module.exports.run (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli-deploy/lib/commands/activate.js:20:25)
    at Class.<anonymous> (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/jpaas/Documents/osaaru/imdhealth/hcp-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickDomainCallback (node.js:381:11)

```

Any suggestions on this one? Near as I can tell it doesn't think there is a revision.

**Comment by LevelbossMike** [comment] 2015-05-27 15:16
This happens when there isn't a revision for the specified environment in the index store.

We should improve the error message on that one ;)

**Comment by jpaas** [comment] 2015-05-27 15:25
Strange because that is the version, I just published immediately before...

```
Upload successful!

Uploaded revision: hcp-webapp:5ec2c0b

(09:21:44) jpaas@megapixel:~/Documents/osaaru/imdhealth/hcp-webapp
$ ember deploy:activate --revision hcp-webapp:5ec2c0b --environment staging​
version: 0.2.5
undefined is not a function
TypeError: undefined is not a function
```

**Comment by LevelbossMike** [comment] 2015-05-27 16:07
did you also deploy to the staging environment?

`ember deploy --environment staging`

**Comment by jpaas** [comment] 2015-05-27 16:08
yes sir

**Comment by charlatan154** [comment] 2015-05-29 12:08
same issue here. 

    Upload successful!

    Uploaded revision: fit-app:0fe6ea0
    0fe6ea0:simple-auth*$ ember deploy:activate --revision 0fe6ea0                       Workspace/fitaborate_www
    version: 0.2.5
    Could not find watchman, falling back to NodeWatcher for file system events.
    Visit http://www.ember-cli.com/#watchman for more info.
    undefined is not a function
    TypeError: undefined is not a function

**Comment by LevelbossMike** [comment] 2015-05-29 13:55
Are you two both using the s3 index adapter?

I think there is either something wrong with your index-store settings or region us-west-2 is behaving in an unexpected way. I am also using the s3-index-adapter on a project and I can't reproduce this issue there.

I am closing this for now because this does not seem to be an issue related to ember-cli-deploy but to the s3-index-adapter. Please raise the issue in the respective adapter's repository.

Please reopen/comment on this issue if this really turns out to be an issue related to ember-cli-deploy directly.

**Comment by LevelbossMike** [comment] 2015-05-29 13:56
This might also be a permission issue on the bucket you are deploying to.

**Closed by LevelbossMike** 2015-05-29 13:55 UTC

**Comment by pzenger** [comment] 2015-05-31 19:54
I'm running into this same issue after following the guide from here  
http://kerrygallagher.co.uk/deploying-an-ember-cli-application-to-amazon-s3/  
  
```
Built project successfully. Stored in "dist/".
Unexpected token u
SyntaxError: Unexpected token u
    at Object.parse (native)
```
etc

**Comment by jpaas** [comment] 2015-06-08 21:40
The original "Unexpected token u" problem has come back for me. EMBER_VERBOSE_ERRORS=true does not show any additional information. Nothing in my configuration has changed.

**Comment by jpaas** [comment] 2015-06-09 13:08
I figured it out. I had a trailing space on my deploy command: `ember deploy --environment staging `. This was setting the environment to "staging " instead of "staging". You way want to do some whitespace trimming on the command line params.

**Comment by lukemelia** [comment] 2015-06-09 13:42
@jpaas Thanks for reporting back. Do you mind opening this as a separate issue?

**Comment by jpaas** [comment] 2015-06-09 13:46
#150 opened

**Comment by lukemelia** [comment] 2015-06-09 13:48
Thanks @jpaas!
